version: '3.0'

services:
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
           POSTGRES_PASSWORD: postgres
        volumes:
            - db_data:/psql
        networks:
          - backend

networks:
    backend:

volumes:
    db_data:
